apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- include "gloo-network-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "cilium.io"
  resources:
  - ciliumendpoints
  verbs:
  - list
  - watch