apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  globalAccessPolicy: DISABLED ##
  mtlsConfig:
    autoRestartPods: true
    shared:
      rootCertificateAuthority:
        generated: {}
  federation:
    selectors:
    - {}
  meshes:
  - name: istiod-istio-system-remotecluster1
    namespace: gloo-mesh
  - name: istiod-istio-system-remotecluster2
    namespace: gloo-mesh
  # - name: istiod-istio-system-cluster2
  #   namespace: gloo-mesh