apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: ui-team
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: '*'
    namespaces:
    - name: webui
    - name: frontend
    - name: catalog