apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: web-team
spec:
  hosts:
    - '*'             # onlineboutique.mycompany.com
  virtualGateways:
    - name: north-south-gw
      namespace: ops-team
      cluster: mgmt-cluster
  http:
    - name: frontend
      matchers:
      - uri:
          prefix: /
      labels:
        route: "frontend"
      forwardTo:
        destinations:
          - ref:
              name: frontend
              namespace: web-ui
              cluster: cluster1
            port:
              number: 80