apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: frontend
  namespace: web-team
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: "true"
  config:
    server:
      name: ext-auth-server
      namespace: web-team
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://35.196.230.78:443
            callbackPath: /callback
            clientId: ce788409-b6f6-4c63-a02e-fc3c05867d5f
            clientSecretRef:
              name: oauth
              namespace: gloo-mesh
            issuerUrl: "http://34.139.6.194:9000/auth/realms/master/"
            logoutPath: /logout
            afterLogoutUrl: "http://34.139.6.194:9000/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fsolo.io"
            scopes:
            - email
            headers:
              idTokenHeader: jwt
