apiVersion: v1
kind: Secret
metadata:
  name: auth0-poc-developer-api-client-secret
  namespace: web-ui
type: extauth.solo.io/oauth
data:
  client-secret: THlBNHVzY0lSLXZndVl3a2FiQW41LTRUU21rMkFYNHczSkVvNGpNYmp0ZW5EVGdFS3Z3R2k5SzZfQWdNZVk5LQ==