# k config use-context rvennam-gm2-mgmt
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: ops
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        cluster: cluster1
  listeners:
    - http: {}
      port:
        name: http2
      allowedRouteTables:
        - host: '*'
    - http: {}
      port:
        name: https
      allowedRouteTables:
        - host: '*'
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: web
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: ops
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: frontend
      forwardTo:
        destinations:
          - ref:
              name: frontend
              namespace: web-ui
            port:
              number: 80