{{/* The purpose of this template is to automatically register the Default Workspace (all namespaces) when the agent subchart is installed */}}

{{- if $.Values.registerMgmtPlane.enabled }}
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: {{ if (and $.Values.global $.Values.global.cluster) -}}{{ if $.Values.mgmtClusterName -}}{{ (eq $.Values.global.cluster "mgmt-cluster") | ternary $.Values.mgmtClusterName $.Values.global.cluster -}}{{ else -}}{{ $.Values.global.cluster -}}{{ end -}}{{ else -}}{{ $.Values.mgmtClusterName -}}{{ end }}
  namespace: {{ $.Release.Namespace }}
spec:
  workloadClusters:
    - name: '*'
      namespaces:
        - name: '*'
---

apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: default
  namespace: {{ $.Release.Namespace }}
spec:
  options:
    serviceIsolation:
      enabled: false
    federation:
      enabled: false
---

{{- end }}
