apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- include "gloo-network-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fullname }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.fullname }}
  namespace: {{ include "gloo-network-agent.namespace" . }}