apiVersion: v1
kind: Namespace
metadata:
  name: ns${x}
  labels:
    app: scale-test
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: scale-test${x}
  namespace: gloo-mesh
  labels:
    app: scale-test
spec:
  workloadClusters:
  - name: 'mgmt-cluster'
    namespaces:
    - name: ns${x}
  - name: '*'
    namespaces:
    - name: ns${x}
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: scale-test${x}
  namespace: ns${x}
  labels:
    app: scale-test
spec:
  options:
    eastWestGateways:
    - selector:
        labels:
          istio: eastwestgateway
    federation:
      enabled: false
    serviceIsolation:
      enabled: false
      trimProxyConfig: false
---
