apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  namespace: gloo-mesh
  name: productpage
spec:
  sourceSelector:
    - kubeIdentityMatcher:
        namespaces:
          - default
        clusters:
          - remotecluster1
  destinationSelector:
    - kubeServiceMatcher:
        namespaces:
          - bookinfo
  allowedPaths:
    - "/foo"
    - "/bar"
  allowedPorts:
    - 9080
  allowedMethods:
    - "GET"