apiVersion: networking.gloo.solo.io/v2
kind: ExternalEndpoint
metadata:
  name: httpbin
  namespace: ops-team
  labels:
    external-service: httpbin
spec:
  address: httpbin.org
  ports:
    # - name: http
    #   number: 80
    - name: https
      number: 443
---
apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: httpbin
  namespace: ops-team
spec:
  selector:
    external-service: httpbin
  hosts:
  - httpbin.org
  ports:
  # - name: http
  #   number: 80
  #   protocol: HTTP
  - name: https
    number: 443
    protocol: HTTPS
    clientsideTls: {}   ### upgrade outbound call to HTTPS