apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: root-trust-policy
  namespace: gloo-mesh
spec:
  config:
    mgmtServerCa: # or Vault agentCa
      generated: {} # let Gloo Mesh handle my certs
    autoRestartPods: true