apiVersion: resilience.policy.gloo.solo.io/v2
kind: FaultInjectionPolicy # or RetryTimeoutPolicy
metadata:
  name: ratings-fault-injection
  namespace: web-team
spec:
  applyToRoutes:
  - route:
      labels:
        route: frontend
  config:
    delay:
      fixedDelay: 3s
      percentage: 100