{{- range $index, $gateway := $.Values.northSouthGateways }}
{{- if $gateway.enabled }}
{{- if ne $index 0 }}
---
{{- end }} 
apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: {{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  installations:
    # ns gateway installation
    - gatewayRevision: {{ $.Values.revision }}
      clusters:
        - name: {{ if $.Values.global }}{{ $.Values.global.cluster }}{{ else }}{{ $.Values.cluster }}{{ end }}
          activeGateway: {{ $.Values.defaultRevision }}
      istioOperatorSpec:
{{ mergeOverwrite (include "northSouthGateways.iopSpec" (dict "Values" $.Values  "Release" $.Release "gateway" $gateway) | fromYaml) $gateway.overrides | toYaml | indent 8 }}

{{- end }}  {{/* if Values.northSouthGateways.enabled */}}
{{- end }}  {{/* range */}}