apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth
  namespace: gloo-mesh
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: http://35.231.243.205:80
        callbackPath: /callback
        clientId: ${client}
        clientSecretRef:
          name: oauth
          namespace: gloo-mesh
        issuerUrl: "http://34.139.6.194:8080/auth/realms/master/"
        scopes:
        - email
        headers:
          idTokenHeader: jwt
