{{- if $.Values.controlPlane.enabled }}
apiVersion: admin.gloo.solo.io/v2
kind: IstioLifecycleManager
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  installations:
    # control plane installation
    - revision: {{ $.Values.revision }}
      clusters:
        - name: {{ if $.Values.global }}{{ $.Values.global.cluster }}{{ else }}{{ $.Values.cluster }}{{ end }}
          defaultRevision: {{ $.Values.defaultRevision }}
      istioOperatorSpec:
{{ mergeOverwrite (include "controlPlane.iopSpec" . | fromYaml) $.Values.controlPlane.overrides | toYaml | indent 8 }}

{{- end }}  {{/* if Values.controlPlane.enabled */}}
