apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ include "gloo-network-agent.namespace" . }}
  labels:
    {{- include "gloo-network-agent.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "gloo-network-agent.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gloo-network-agent.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.hub }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.fullname }}
        args:
        {{- include "gloo-network-agent.cmd.args" . | nindent 8 }}
#        TODO: (SirNexus) do we want to unload the bpf programs before stop?
#        lifecycle:
#          preStop:
#            exec:
#              command:
#              {{/* {{- include "gloo-network-agent.cmd.clean" . | nindent 14 }} */}}
        resources: 
          requests:
            cpu: {{ .Values.resources.container.request.cpu }}
            memory: {{ .Values.resources.container.request.memory }}
          limits:
            cpu: {{ .Values.resources.container.limit.cpu }}
            memory: {{ .Values.resources.container.limit.memory }}
        securityContext:
          capabilities:
            add:
              - SYS_RESOURCE
              - SYS_ADMIN
        volumeMounts:
          - mountPath: /sys/fs/bpf
            name: bpf-maps
      nodeSelector:
        {{- include "gloo-network-agent.nodeSelector" . | nindent 8 }}
      restartPolicy: Always
      serviceAccount: {{ .Values.fullname }}
      serviceAccountName: {{ .Values.fullname }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps